#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-gson
Version  : 2.2.4
Release  : 2
URL      : https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Source0  : https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Source1  : https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
Source2  : https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar
Source3  : https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-gson-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-gson package.
Group: Data

%description data
data components for the mvn-gson package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.2.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.2.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.3.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.3.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
/usr/share/java/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
/usr/share/java/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar
/usr/share/java/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.pom
